class User {
  final int iduser, idrole, idagent, idvendor, agentIduser;
  final String firstName,
      lastName,
      userName,
      email,
      password,
      entrepriseName,
      ice,
      city,
      address,
      telephone,
      agentName,
      profileImage,
      agentPhone,
      code,
      firstConnection;

  User(
    this.iduser,
    this.idagent,
    this.firstName,
    this.lastName,
    this.userName,
    this.email,
    this.password,
    this.entrepriseName,
    this.ice,
    this.city,
    this.address,
    this.telephone,
    this.idvendor,
    this.agentIduser,
    this.agentName,
    this.idrole,
    this.profileImage,
    this.agentPhone,
    this.code,
    this.firstConnection,
  );

  dynamic toJson() => {
        'iduser': iduser,
        'idagent': idagent,
        'firstName': firstName,
        'lastName': lastName,
        'userName': userName,
        'email': email,
        'password': password,
        'entrepriseName': entrepriseName,
        'ice': ice,
        'city': city,
        'address': address,
        'telephone': telephone,
        'code': idvendor,
        'agentIduser': agentIduser,
        'agentName': agentName,
        'idrole': idrole,
        'profileImage': profileImage,
        'agentPhone': agentPhone,
        'code': code,
        'firstConnection': firstConnection,
      };

  User.fromJson(Map<String, dynamic> json)
      : iduser = json['iduser'],
        idagent = json['idagent'],
        firstName = json['firstName'],
        lastName = json['lastName'],
        userName = json['userName'],
        email = json['email'],
        password = json['password'],
        entrepriseName = json['entrepriseName'],
        ice = json['ice'],
        city = json['city'],
        address = json['address'],
        telephone = json['telephone'],
        idvendor = json['idvendor'],
        agentIduser = json['agentIduser'],
        agentName = json['agentName'],
        idrole = json['idrole'],
        profileImage = json['profileImage'],
        agentPhone = json['agentPhone'],
        code = json['code'],
        firstConnection = json['firstConnection'];
}
